trigger: none

pool:
  name: Default
stages:
  - stage: Test
    jobs:
      - job: Secrets
        displayName: 'Retrieve Secrets'
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'BetterBoard Dev' # Azure subscription name
              KeyVaultName: 'bbkeyvaultselenium'
              SecretsFilter: 'griduri,apikey,testcreds'
          - task: UseDotNet@2
            displayName: 'Use .NET SDK version 8.0.301'
            inputs:
              version: 8.0.301
          - task: DotNetCoreCLI@2
            displayName: 'Restore Solution'
            inputs:
              command: restore
              projects: './src/WebDriverTests/WebDriverTests.sln'
          - task: DotNetCoreCLI@2
            displayName: 'Build Solution'
            inputs:
              command: build
              projects: './src/WebDriverTests/WebDriverTests.sln'
              arguments: '--no-restore'
          - task: DotNetCoreCLI@2
            displayName: 'Execute Tests'
            env:
              GRID_URI: $(griduri)
              API_KEY: $(apikey)
              TARGET_URI: 'https://dev.betterboard.dk/'
              TEST_CREDS: $(testcreds)
            inputs:
              command: test
              projects: './src/WebDriverTests/WebDriverXUnit/WebDriverXUnit.csproj'
              arguments: '--no-restore --no-build --logger "console;verbosity=detailed"'