name: Deploy Aspire
on: workflow_dispatch
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: selenium-env
      AZURE_LOCATION: westeurope
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 

      - name: Deploy bicep
        run: |
          az deployment sub create --name selenium-deployment --location westeurope --template-file ./src/Aspire/infra/main.bicep