name: build-dotnet-webdriver-project

on: workflow_dispatch

run-name: build-dotnet-webdriver-project

defaults:
    run:
        shell: bash
        working-directory: src/WebDriverTests

jobs:

    build:

        name: Build .Net 8 WebDriver project

        runs-on: self-hosted

        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: dotnet restore
              run: dotnet restore WebDriverTests.sln
            
            - name: dotnet build
              run: dotnet build --no-restore WebDriverTests.sln