name: build-dotnet-webdriver-project

on: workflow_dispatch

run-name: build-dotnet-webdriver-project

jobs:

    build:

        name: Build .Net 8 WebDriver project

        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            - run: dotnet build WebDriverTests.sln
              working-directory: src/WebDriverTests