name: Acceptance Tests Through GUI

# Manual trigger with `gh workflow run <workflow_name>`
on: workflow_dispatch

run-name: Acceptance Tests Through GUI

defaults:
    run:
        shell: bash

jobs:

    runidentifier:
      
      name: Generate unique identifier for this action run

      runs-on: self-hosted

      outputs:
        outputid: ${{ steps.idstep.outputs.identifier }}
        outputobjectid: ${{ steps.objectidstep.outputs.objectid }}

      steps:

        - name: checkout
          uses: actions/checkout@v4

        - id: idstep
          run: echo "identifier=$(uuidgen | tr -d '-')" >> $GITHUB_OUTPUT

        - id: objectidstep
          run: echo "objectid=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 24)" >> $GITHUB_OUTPUT

    seed:

      name: Set-up for test

      runs-on: self-hosted

      needs: runidentifier

      steps:
        
        - name: Execute permissions
          run: chmod +x ./src/test-transaction/setup.sh

        # - name: setup script
        #   run: ./src/test-transaction/setup.sh ${{ secrets.API_KEY }} ${{ needs.runidentifier.outputs.outputid }} ${{ needs.runidentifier.outputs.outputobjectid }}

        - name: setup script
          run: |
            curl --location "https://devapi.betterboard.dk/api/v1/testtransaction/start" --header "X-Api-Key: ${{ secrets.API_KEY }}" --header "Content-Type: application/json" --data "{ "Id": "${{ needs.runidentifier.outputs.outputid }}", "CompanyId": "${{ needs.runidentifier.outputs.outputobjectid }}" }"

    build:

        name: Build .Net 8 WebDriver project

        runs-on: self-hosted

        continue-on-error: true

        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: dotnet restore
              run: dotnet restore ./src/WebDriverTests/WebDriverTests.sln
            
            - name: dotnet build
              run: dotnet build --no-restore ./src/WebDriverTests/WebDriverTests.sln
    
    test:

        needs:
          - build
          - seed

        name: Run Selenium Scripts

        runs-on: self-hosted

        continue-on-error: true

        steps:

            - name: Set execute permissions for shell script
              run: chmod +x ./src/WebDriverTests/wait_for_grid.sh

            - name: Healthcheck Selenium Grid
              env:
                GRID_URI: ${{ secrets.GRID_URI }}
              run: ./src/WebDriverTests/wait_for_grid.sh -u $GRID_URI

            - name: Execute WebDriver tests
              env:
                GRID_URI: ${{ secrets.GRID_URI }}
                TEST_USERS: ${{ secrets.TEST_USERS }}
                API_KEY: ${{ secrets.API_KEY }}
                RUNTIME_ENVIRONMENT: STAGING 
              run: dotnet test --no-restore --no-build --logger "console;verbosity=detailed" --filter WebDriverXUnit.Tests.Authentication.FirefoxSmokeTest ./src/WebDriverTests/WebDriverXUnit/WebDriverXUnit.csproj

    teardown:

      name: teardown

      runs-on: self-hosted

      needs:
        - seed
        - test

      steps:

        - name: execution permissions
          run: chmod +x ./src/test-transaction/cleanup.sh

        # - name: teardown script
        #   run: ./src/test-transaction/cleanup.sh ${{ secrets.API_KEY }} ${{ needs.runidentifier.outputs.outputid }} ${{ needs.runidentifier.outputs.outputobjectid }}

        - name: teardown script
          run: |
            curl --location --request DELETE "https://devapi.betterboard.dk/api/v1/testtransaction/cleanup" --header "X-Api-Key: ${{ secrets.API_KEY }}" --header "Content-Type: application/json" --data "{ "Id": "${{ needs.runidentifier.outputs.outputid }}", "CompanyId": "${{ needs.runidentifier.outputs.outputobjectid }}" }"