name: Build & Execute Tests .Net WebDriver project

# Manual trigger with `gh workflow run <workflow_name>`
on: workflow_dispatch

run-name: build-dotnet-webdriver-project

defaults:
    run:
        shell: bash
        working-directory: src/WebDriverTests

jobs:

    build:

        name: Build .Net 8 WebDriver project

        runs-on: self-hosted

        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: dotnet restore
              run: dotnet restore WebDriverTests.sln
            
            - name: dotnet build
              run: dotnet build --no-restore WebDriverTests.sln
    
    test:

        needs: build

        name: Run Selenium Scripts

        runs-on: self-hosted

        steps:

            - name: Set execute permissions for shell script
              run: chmod +x ./wait_for_grid.sh

            - name: Healthcheck Selenium Grid
              run: ./wait_for_grid.sh